apiVersion: v1
kind: Secret
metadata:
  name: rss-app-secrets
  namespace: default
type: Opaque
stringData:
  # Database credentials
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
  
  # Kafka credentials (if needed)
  SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: ""
  SPRING_KAFKA_PROPERTIES_SASL_MECHANISM: ""
  SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL: ""
